id: I7595B16F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T10:33:23+00:00'
last_modified: '2022-06-07T20:48:28.512596+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14630
  title: འཇིགས་བྱེད་ཀྱི་བསྐྱེད་རྫོགས་ཀྱི་ཁྲིད་ཡིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedSealed
  restrictedInChina: false
  base:
    58CF:
      image_group_id: I1KG14643
      title: ''
      total_pages: 694
      order: 1
      base_file: 58CF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
